{% set name = "jupyterlab-logtalk-codemirror-extension" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_logtalk_codemirror_extension-{{ version }}.tar.gz
  sha256: 9e4c1fc6478ca7448bd061d1ca0e8e8b80ff105d12c7d4bcee1188e9a96369d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder
    - nodejs
    - pip
  run:
    - python >={{ python_min }}
    - nodejs
    - jupyterlab >=4.0.0,<5

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/jupyterlab-logtalk-codemirror-extension
  summary: A JupyterLab extension for Logtalk syntax highlighting.
  dev_url: https://github.com/LogtalkDotOrg/jupyterlab-logtalk-codemirror-extension
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    A JupyterLab 4.x extension providing a Logtalk CodeMirror mode for syntax highlighting.

extra:
  recipe-maintainers:
    - pmoura
